using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.WinForms;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace MSCCargoYHavy;
public sealed class MainForm:Form {
 readonly WebView2 browser=new(); readonly ToolStrip strip=new(); readonly ToolStripButton back=new("‹"), forward=new("›"), refresh=new("⟳"), home=new("Home"); readonly ToolStripLabel appTitle=new(AppConfig.AppName); readonly StatusStrip statusStrip=new(); readonly ToolStripStatusLabel status=new("Starting...");
 public MainForm(){ Text=AppConfig.AppName; StartPosition=FormStartPosition.CenterScreen; MinimumSize=new Size(960,640); Size=new Size(1366,850); BuildUi(); Shown+=async(_,_)=>await InitAsync(); FormClosing+=(_,_)=>browser.Dispose(); }
 void BuildUi(){ strip.GripStyle=ToolStripGripStyle.Hidden; strip.Padding=new Padding(6,4,6,4); foreach(var b in new[]{back,forward,refresh,home}){b.DisplayStyle=ToolStripItemDisplayStyle.Text;b.AutoSize=false;b.Width=55;b.Height=30;strip.Items.Add(b);} appTitle.Alignment=ToolStripItemAlignment.Right;appTitle.Font=new Font("Segoe UI",9,FontStyle.Bold);strip.Items.Add(appTitle); back.Click+=(_,_)=>{if(browser.CoreWebView2?.CanGoBack==true)browser.CoreWebView2.GoBack();}; forward.Click+=(_,_)=>{if(browser.CoreWebView2?.CanGoForward==true)browser.CoreWebView2.GoForward();}; refresh.Click+=(_,_)=>browser.CoreWebView2?.Reload(); home.Click+=(_,_)=>NavigateStartup(); browser.Dock=DockStyle.Fill; statusStrip.Items.Add(status); Controls.Add(browser);Controls.Add(statusStrip);Controls.Add(strip); }
 async Task InitAsync(){try{var folder=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MSC CargoYHavy","WebView2");Directory.CreateDirectory(folder);var env=await CoreWebView2Environment.CreateAsync(null,folder);await browser.EnsureCoreWebView2Async(env);var c=browser.CoreWebView2;c.Settings.IsStatusBarEnabled=false;c.Settings.AreDevToolsEnabled=false;c.Settings.AreDefaultContextMenusEnabled=true;c.Settings.IsZoomControlEnabled=true;c.Settings.IsPasswordAutosaveEnabled=true;c.Settings.IsGeneralAutofillEnabled=true;c.NavigationStarting+=(_,_)=>{status.Text="Loading...";UpdateNav();};c.NavigationCompleted+=(_,e)=>{status.Text=e.IsSuccess?"Connected • MSC CargoYHavy":"Page could not be loaded";UpdateNav();};c.HistoryChanged+=(_,_)=>UpdateNav();c.NewWindowRequested+=(_,e)=>{e.Handled=true;c.Navigate(e.Uri);};c.DownloadStarting+=(_,e)=>{var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Downloads");Directory.CreateDirectory(d);var n=Path.GetFileName(e.ResultFilePath);if(string.IsNullOrWhiteSpace(n))n="download";e.ResultFilePath=Path.Combine(d,n);};c.LaunchingExternalUriScheme+=(_,e)=>{try{Process.Start(new ProcessStartInfo{FileName=e.Uri,UseShellExecute=true});e.Cancel=true;}catch{}};NavigateStartup();}catch(Exception ex){status.Text="Web engine startup failed";MessageBox.Show("MSC CargoYHavy could not initialize Microsoft Edge WebView2.\n\nPlease install the WebView2 Runtime and restart.\n\n"+ex.Message,AppConfig.AppName,MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 void NavigateStartup(){if(browser.CoreWebView2==null)return;browser.CoreWebView2.Navigate(string.IsNullOrWhiteSpace(AppConfig.DashboardUrl)?AppConfig.RegistrationUrl:AppConfig.DashboardUrl);}
 void UpdateNav(){if(browser.CoreWebView2==null)return;back.Enabled=browser.CoreWebView2.CanGoBack;forward.Enabled=browser.CoreWebView2.CanGoForward;}
}
